### ISSUE TITLE
Update check for unset override_allele_scheme to include empty string

### ISSUE THREAD

**Issue by apetkau** [phac-nml/mikrokondo#107]
### Description of feature

Currently, the parameter `override_allele_scheme` is considered unset only if it has a value of `null`. See for example:

https://github.com/phac-nml/mikrokondo/blob/c32ce856fbac0e017f7b1d6111a12feaf59eaff5/subworkflows/local/locidex.nf#L26-L30

Within IRIDA Next, I wish to configure allele schemes so they are set using drop-down values like below:

![image](https://github.com/user-attachments/assets/aea82d50-91ae-4116-8a7c-2fa1de1fb6fc)

I wish to have an option **Automated selection from allele database**, which will be used to indicate that the `override_allele_scheme` should be skipped and automated database selection should be performed. This is the equivalent of setting `override_allele_scheme = null`.

However, in IRIDA Next, you cannot override parameters and set to `null`, they must be strings. Hence, I would like both `override_allele_scheme = null` and `override_allele_scheme = ""` to be treated identically.

**Comment by mattheww95** [comment]
I there may be some additional changes to some control flow logic in the `subworkflows/local/locidex.nf` but I think replacing `null` with "" would work out well!

I can start work on this tommorow if you would like. Would this have to be rolled out as part of a patch or do you see it being released in the next minor release?

**Comment by apetkau** [comment]
Thanks. Should be a patch, but doesn't have to be immediate.

**Comment by mattheww95** [comment]
fixed in [PR 109](https://github.com/phac-nml/mikrokondo/pull/109)
