### ISSUE TITLE
Create identification fields

### ISSUE THREAD

**Issue by jrober84** [phac-nml/mikrokondo#81]
### Description of feature

Taxonomic identifications may be provided by multiple different tools within MikroKondo and may not resolve to the species identification level ie. Genus or full resolution to subspecies. So MikroKondo should create fields called "predicted_identification_name", "predicted_identification_method" where the name field is populated with the final identification for the sample, and the method should contain the name of the software tool used for the final identification. In the case of a metagenomic sample with multiple taxa this needs some clarification as to whether it would be populated. For version 1, I suggest that it only is populated for single taxon samples and only contains the identification information. ie. s___Salmonella enterica should be Salmonella enterica and the method used for identification ie. mash.

**Comment by mattheww95** [comment]
Fixed in PR https://github.com/phac-nml/mikrokondo/pull/90
