### ISSUE TITLE
Wrong labels for sistr results in aggregated report

### ISSUE THREAD

**Issue by jrober84** [phac-nml/mikrokondo#82]
### Description of the bug

All of the sistr data fields appear to be shifted by 1
ie. 
SISTRSubtyping.0.cgmlst_ST is actually SISTRSubtyping.0.cgmlst_distance
SISTRSubtyping.0.cgmlst_distance is actually SISTRSubtyping.0.cgmlst_found_loci

and so forth. This data was produced by @mattheww95 on the UAT dataset

**Comment by mattheww95** [comment]
Thank you for finding this issue! noticed it is due to an empty column output value in the output by sistr cause the shift. I will take care of that. I am attaching an image for reference.

![image](https://github.com/phac-nml/mikrokondo/assets/76452933/9a3dca37-9252-45c0-ad66-2d93ce93413b)

**Comment by apetkau** [comment]
This was fixed in #83
